name: Build qjsc.wasm Builder image and WASM Binary using Docker

on:
  push:
    branches: [ "main", "dev" ]
  pull_request:
    branches: [ "main", "dev" ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  wasmbuild:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker container
        run: docker build --tag quickjs-wasm-builder .

      - name: Run Docker Container to build qjsc
        run: mkdir -p ${{ github.workspace }}/build && touch ${{ github.workspace }}/build/qjsc.wasm && docker run --rm --platform linux/amd64 -v ${{ github.workspace }}/build:/wasi/build quickjs-wasm-builder qjsc

      - name: Upload artifact compiler, qjsc.wasm
        uses: actions/upload-artifact@v4
        with:
          name: qjsc.wasm
          path: build/qjsc.wasm

      - name: Run Docker Container to build qjs
        run: mkdir -p ${{ github.workspace }}/build && touch ${{ github.workspace }}/build/qjs.wasm && docker run --rm --platform linux/amd64 -v ${{ github.workspace }}/build:/wasi/build quickjs-wasm-builder qjs

      - name: Upload artifact runtime, qjs.wasm
        uses: actions/upload-artifact@v4
        with:
          name: qjs.wasm
          path: build/qjs.wasm
