name: Build qjsc.wasm Builder image and WASM Binary using Docker

on:
  push:
    branches: [ "main", "dev" ]
  pull_request:
    branches: [ "main", "dev" ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  builder:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Cache Docker layers
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Build Docker container
        run: docker build --tag quickjs-wasm-builder .

      - name: Run Docker container
        run: docker run --rm --platform linux/amd64 -v ${{ github.workspace }}/build:/wasi/build quickjs-wasm-builder qjsc

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: qjsc-wasm
          path: build/qjsc.wasm
